name: Test

on:
  push:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }} # For each os, run this job on it.
    steps:
    - name: Run the Tests
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: ctest -V -C $BUILD_TYPE
